### PR TITLE
[flink] Fix CI compilation error: adapt test to int[] nullCounts signature

### LINKED ISSUE #3061: [flink] CI compilation failure in FlinkTableSourceFilterPushDownTest after #3054
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.9.0 (latest release)

### Please describe the bug 🐞

After merging #3054 and #3032, the CI `flink` stage fails with compilation errors in `FlinkTableSourceFilterPushDownTest`.

### Solution

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by platinumhamburg**
### Purpose

Linked issue: close #3061 3061

### CODE REVIEW

**Review by swuferhong — APPROVED** [review]
LGTM
