### ISSUE TITLE
[flink] CI compilation failure in FlinkTableSourceFilterPushDownTest after #3054

### ISSUE THREAD

**Issue by platinumhamburg** [alibaba/fluss#3061]
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/fluss/issues) and found nothing similar.

### Fluss version

0.9.0 (latest release)

### Please describe the bug 🐞

After merging #3054 and #3032, the CI `flink` stage fails with compilation errors in `FlinkTableSourceFilterPushDownTest`.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!
